### ISSUE TITLE
make sure to comment main parts of code

### ISSUE THREAD

**Issue by ad3429** [huinni/prj-rev-bwfs-dasmoto#3]
https://github.com/huinni/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtstnCrafts/index.html#L1-L30

In future projects, it may be a good idea to comment the main parts of your code. This becomes increasingly important as your projects grow and become more complex. Here is a quick reminder on commenting in HTML:

<img width="197" alt="html_comment" src="https://user-images.githubusercontent.com/25671399/45261179-039a2700-b3ca-11e8-900f-a332402736e3.png">

**Comment by huinni** [comment]
Got it.
