### ISSUE TITLE
CSS is clean and succinct

### ISSUE THREAD

**Issue by ad3429** [huinni/prj-rev-bwfs-dasmoto#4]
https://github.com/huinni/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtstnCrafts/resources/css/style.css#L1-L25

Your CSS is short and succinct -- good job! An area of improvement is to make sure to comment your main stylings. Here is a quick reminder on commenting in CSS:

<img width="178" alt="css comment" src="https://user-images.githubusercontent.com/25671399/45261181-16146080-b3ca-11e8-8940-e1aa2eabec6e.png">

**Comment by huinni** [comment]
Good to know. Is it industry's standard to comment?
